export const notes = [
    { id: '1', title: 'Grocery List', desc: 'Buy milk, eggs, bread, and fruits.' },
    { id: '2', title: 'Meeting Notes', desc: 'Discuss project milestones and deadlines for the upcoming quarter. Ensure that all team members are aligned with the new objectives and review the progress on current tasks.' },
    { id: '3', title: 'Travel Plans', desc: 'Book flights and hotels for the upcoming trip. Make sure to confirm all reservations and check travel advisories. Prepare a list of places to visit and activities to do during the stay.' },
    { id: '4', title: 'Workout Routine', desc: 'Morning yoga, afternoon gym, and evening walk. Include stretching exercises and focus on different muscle groups each day. Maintain a balanced diet and stay hydrated throughout the day.' },
    { id: '5', title: 'Ideas for Blog', desc: 'Write about tech trends, programming tips, and personal experiences. Explore topics like machine learning, web development frameworks, and productivity hacks. Share insights and practical advice for readers interested in technology.' },
    { id: '6', title: 'Reading List', desc: 'Finish reading "Clean Code" and "The Pragmatic Programmer". Add more books to the list such as "Design Patterns" and "Refactoring". Aim to read at least one book per month to continuously improve programming skills.' },
    { id: '7', title: 'Dinner Recipe', desc: 'Prepare lasagna with garlic bread and a side salad. Cook the lasagna layers separately and then combine them. Use fresh ingredients and seasonings to enhance flavor. Ensure that the garlic bread is crispy and the salad is well-dressed.' },
    { id: '8', title: 'Project Tasks', desc: 'Complete UI design and implement authentication. Develop a user-friendly interface with intuitive navigation. Integrate secure authentication methods and perform thorough testing to ensure everything functions correctly before the final release.' },
    { id: '9', title: 'Weekend Activities', desc: 'Hike in the morning, visit museum in the afternoon. Explore new trails and enjoy nature. In the afternoon, take a trip to the museum to learn about art and history. End the day with a relaxing dinner.' },
    { id: '10', title: 'Shopping List', desc: 'Buy new shoes, get a haircut, and pick up dry cleaning. Make sure to choose comfortable shoes and schedule a haircut appointment. Don’t forget to collect the dry cleaning items before they close for the day.' },
    { id: '11', title: 'Event Planning', desc: 'Organize the office party and send invitations. Plan the event details such as venue, catering, and entertainment. Send out invitations to all employees and follow up to ensure everyone has RSVP’d. Prepare a schedule for the event.' },
    { id: '12', title: 'Vacation Packing', desc: 'Pack clothes, toiletries, and travel documents for the trip. Make a checklist to ensure nothing is forgotten. Include items like sunscreen, medication, and chargers. Review the packing list to confirm that everything is ready for the trip.' },
    { id: '13', title: 'Movie Watchlist', desc: 'Watch "Inception", "The Matrix", and "Interstellar". Explore movies that involve complex narratives and deep themes. Consider creating a list of must-watch films and schedule regular movie nights to enjoy these films with friends.' },
    { id: '14', title: 'Daily Routine', desc: 'Wake up early, exercise, work, and relax in the evening. Establish a morning routine that includes exercise and a healthy breakfast. Follow a productive work schedule and ensure to wind down with relaxing activities before bed.' },
    { id: '15', title: 'Personal Goals', desc: 'Learn a new language and complete a marathon. Set specific milestones for learning and practicing the new language. Train regularly for the marathon and follow a structured plan to improve endurance and performance.' },
  ];
  